const {chromium}=require('playwright'),fs=require('fs');
const out='/qa-output/growth-pass/'+(process.env.WB_BASELINE?'before':process.env.WB_PUBLIC_QA?'public':'preview');fs.mkdirSync(out,{recursive:true});
const config=JSON.parse(fs.readFileSync('/qa/config.json','utf8'));
const url=path=>'https://worksbetter.ai'+path+(process.env.WB_BASELINE||process.env.WB_PUBLIC_QA?'':'?wpvibe_preview='+encodeURIComponent(config.token));
const checks=[],errors=[],observations=[];
const check=(name,pass)=>{checks.push({name,pass:!!pass});if(!pass)throw Error(name)};
(async()=>{const browser=await chromium.launch({headless:true,proxy:{server:process.env.HTTPS_PROXY}});try{
for(const width of [1440,894,390,320]){const ctx=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});
await ctx.route('**/*',r=>new URL(r.request().url()).hostname==='worksbetter.ai'&&r.request().method()==='GET'?r.continue():r.abort());
const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(url('/'),{waitUntil:'networkidle'});
const observationsPage=await page.evaluate(()=>{const hero=document.querySelector('.wb-commercial-hero'),old=document.querySelector('.flagship-entry');const first=hero?.querySelector('[data-contact]')||old?.querySelector('.button');const r=first?.getBoundingClientRect();return{documentHeight:document.documentElement.scrollHeight,firstBodyActionY:r?.y,firstBodyActionBottom:r?.bottom,firstBodyActionLabel:first?.innerText,heroHasPaidExpectations:hero?.innerText.includes('Scope and fees'),heroWordCount:(hero?.querySelector('.wb-hero-copy')||document.querySelector('.hero-invitation'))?.innerText.split(/\s+/).length,headerDestinations:[...document.querySelectorAll('nav[aria-label="Main navigation"]>a')].map(a=>a.innerText)}});
observations.push({width,...observationsPage});await page.screenshot({path:out+`/home-${width}.png`});
if(process.env.WB_BASELINE){await ctx.close();continue;}
check(`${width}: HTTPS200`,response.status()===200);check(`${width}: one H1`,await page.locator('h1').count()===1);check(`${width}: no horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(`${width}: hero enquiry within900px`,observationsPage.firstBodyActionBottom<=900);check(`${width}: upfront paid expectations`,observationsPage.heroHasPaidExpectations);check(`${width}: old repeated card absent`,await page.locator('.flagship-entry').count()===0);check(`${width}: optional AI closed`,!(await page.locator('.wb-idea-details').evaluate(e=>e.open)));check(`${width}: one Guides link`,await page.locator('nav[aria-label="Main navigation"] .guide-nav-link').count()===1);
check(`${width}: FAQ has two grid children`,await page.locator('#working-together > div').count()===2&&await page.locator('#working-together > details').count()===0);check(`${width}: software answer in FAQ column`,await page.locator('#working-together > div:nth-child(2) details').filter({has:page.locator('summary',{hasText:'Can we keep using our existing software?'})}).count()===1);check(`${width}: FAQ example direction accurate`,!(await page.locator('main').innerText()).includes('six worked examples below'));
await page.locator('.wb-hero-actions [data-contact]').click();check(`${width}: hero opens enquiry`,await page.locator('#contact-dialog').evaluate(e=>e.open));check(`${width}: concise enquiry expectations`,(await page.locator('#contact-dialog').innerText()).includes('Scope and fees are agreed'));await page.keyboard.press('Escape');check(`${width}: Escape closes enquiry`,!(await page.locator('#contact-dialog').evaluate(e=>e.open)));
await page.locator('.wb-hero-actions a').click();check(`${width}: example destination`,new URL(page.url()).hash==='#playground');await page.goto(url('/'),{waitUntil:'networkidle'});
const select=page.locator('#wb-proof-case'),next=page.locator('#wb-proof-next'),status=page.locator('#wb-proof-status');
await next.click();await next.click();check(`${width}: human approval required`,(await status.innerText()).includes('still decides')&&await next.innerText()==='Approve invoice');await next.click();check(`${width}: approved connections, no payment`,(await status.innerText()).includes('Google Drive')&&(await status.innerText()).includes('No payment occurs'));check(`${width}: completed terminal`,await next.isDisabled());
await select.selectOption('duplicate');await next.click();check(`${width}: duplicate terminal`,await next.isDisabled()&&(await status.innerText()).includes('nothing is filed'));
await select.selectOption('mismatch');await next.click();await next.click();await next.click();check(`${width}: mismatch needs explanation`,await page.locator('#wb-proof-reason').getAttribute('aria-invalid')==='true'&&!(await next.isDisabled()));await page.locator('#wb-proof-reason').fill('Fictional agreed scope explains the difference.');await next.click();check(`${width}: explained approval completes`,await next.isDisabled()&&(await status.innerText()).includes('approver details'));
await page.locator('#wb-proof-reset').click();await next.click();await next.click();await page.locator('#wb-proof-decline').click();check(`${width}: decline stops`,await next.isDisabled()&&(await status.innerText()).includes('Declined'));await page.locator('#wb-proof-reset').click();check(`${width}: reset restores first step`,!(await next.isDisabled())&&await next.innerText()==='Check MYOB');await page.locator('.wb-proof-card').screenshot({path:out+`/decision-${width}.png`});
await page.locator('[data-delivery-mode="automatic"]').click();check(`${width}: mode enquiry label is truthful`,(await page.locator('[data-delivery-mode="automatic"]').innerText()).includes('Discuss'));check(`${width}: selected mode retained`,await page.locator('#contact-run').inputValue()==='automatic');await page.keyboard.press('Escape');
await page.goto(url('/')+'#your-idea',{waitUntil:'networkidle'});check(`${width}: legacy idea link opens tool`,await page.locator('.wb-idea-details').evaluate(e=>e.open));check(`${width}: disclosure and tool reachable`,await page.locator('#own-idea').isVisible()&&await page.locator('#play-disclosure').isVisible());await page.locator('#own-idea').fill('short');await page.locator('#imagine-button').click();check(`${width}: tool validation remains`,!(await page.locator('#own-idea').evaluate(e=>e.checkValidity()))||(await page.locator('#idea-error').innerText()).includes('12 to 2,000'));
await ctx.close();}
check('no uncaught browser errors',errors.length===0);fs.writeFileSync(out+'/qa.json',JSON.stringify({scope:'Actual WordPress HTTPS with only site GET and intercepted client interactions; no notifications or external analytics sent',checks,errors,observations},null,2));console.log(JSON.stringify({checks:checks.length,errors,observations}));
}finally{await browser.close()}})().catch(e=>{console.error(e);fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,observations,error:e.message},null,2));process.exit(1)});
